export const skills = [
    {name: "Html", level: 95, category: "frontend"},
    {name: "javaScript", level: 95, category: "frontend"},
    {name: "react", level: 90, category: "frontend"},
    {name: "typeScript", level: 95, category: "frontend"},
    {name: "Tailwind", level: 90, category: "frontend"},
    {name: "Next.js", level: 95, category: "frontend"},

    {name: "Node.js", level: 90, category: "backend"},
    {name: "Express", level: 95, category: "backend"},
    {name: "Mongo", level: 90, category: "backend"},
    {name: "PosgreSQL", level: 95, category: "backend"},
    {name: "GraphQL", level: 90, category: "backend"},
    {name: "Django", level: 90, category: "backend"},

    {name: "Git/GitHub", level: 90, category: "tools"},
    {name: "Docker", level: 95, category: "tools"},
    {name: "Figma", level: 90, category: "tools"},
    {name: "Vs", level: 95, category: "tools"},
    
];

export const projects = [
    {
       id: 1,
       title: "Todo app",
       des: "This app alows you write your todos, it has crud operation and also alarm system which serves as reminder",
       image: "/projects/todo.png",
       tags: ["React", "Tailwind", "Django"],
       demoUrl: "yiltongs-todo.netlify.app",
       githubUrl: "github.com/Yiltong/todoApp",      
    },
    {
       id: 2,
       title: "Voting app",
       des: "This is a front end app created with only react.js, it is a voting app that alows you to vote for a candidate, delete a candidate and also add election",
       image: "/projects/voting.png",
       tags: ["React", "Tailwind", "Django"],
       demoUrl: "yiltongs-voting.netlify.app",
       githubUrl: "github.com/Yiltong/VotingApps",      
    },
    {
       id: 3,
       title: "ecomerce",
       des: "This is an ecomerce app, it is user freindly, it has both backend and frontend",
       image: "/projects/e-com.png",
       tags: ["React", "Tailwind", "Node.js"],
       demoUrl: "yiltongs-ecom.netlify.app",
       githubUrl: "github.com/Yiltong/ecomerce",      
    },
    {
       id: 4,
       title: "Weather App",
       des: "This app shows the weather of a city. you type the name of the city, and it shows you the temperature, humidity and wind i use weather api and react.js",
       image: "/projects/weathwe.png",
       tags: ["React", "css", "weather Api"],
       demoUrl: "yiltongs-weather.netlify.app",
       githubUrl: "github.com/Yiltong/WeaterApp",      
    },
    {
       id: 5,
       title: "My portfolio",
       des: "This app was build using react.js and tailwind css, it showws my skills and qualification",
       image: "/projects/Screenshot 2025-11-26 094025.png",
       tags: ["React", "Tailwind"],
       demoUrl: "yilongs-port.netlify.app",
       githubUrl: "#",      
    },
    {
       id: 5,
       title: "My certificate",
       des: "",
       image: "/projects/Certificate.jpg",
       tags: ["React", "Tailwind"],
       demoUrl: "#",
       githubUrl: "#",      
    },
    {
       id: 5,
       title: "My certificate",
       des: "Simplilearn Django certificate",
       image: "/projects/djan.png",
       tags: ["React", "Tailwind"],
       demoUrl: "#",
       githubUrl: "#",      
    },
    {
       id: 5,
       title: "My certificate",
       des: "Simplilearn Artificial inteligence certificate ",
       image: "/projects/arti.png",
       tags: ["React", "Tailwind"],
       demoUrl: "#",
       githubUrl: "#",      
    },
]

